const fs = require('fs');
let fileContent = fs.readFileSync('webapp/controller/Employees.controller.js', 'utf8');

const regex = /items:\s*\[([\s\S]*?)\]\s*}\);/;
const match = fileContent.match(regex);
if (match) {
    const newData = `items: [
                        { id: "EMP0001", EmployeeCode: "EMP0001", FirstName: "Ahmed", LastName: "Al-Salem", DepartmentName: "IT", LocationName: "Dammam", Email: "ahmed.alsalem@example.com", Phone: "+966500000001", Designation: "IT Manager", JoiningDate: "2020-01-15", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT001", DepartmentUuid: "DEP-01", LocationUuid: "LOC-01", ManagerUuid: "" },
                        { id: "EMP0002", EmployeeCode: "EMP0002", FirstName: "Vijayan", LastName: "Kumar", DepartmentName: "IT", LocationName: "Riyadh", Email: "vijayan.kumar@example.com", Phone: "+966500000002", Designation: "Software Engineer", JoiningDate: "2021-03-10", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT002", DepartmentUuid: "DEP-01", LocationUuid: "LOC-02", ManagerUuid: "EMP0001" },
                        { id: "EMP0003", EmployeeCode: "EMP0003", FirstName: "Sara", LastName: "Hassan", DepartmentName: "Finance", LocationName: "Jeddah", Email: "sara.hassan@example.com", Phone: "+966500000003", Designation: "Financial Analyst", JoiningDate: "2019-06-20", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "SAP HR", ExternalEmployeeId: "EXT003", DepartmentUuid: "DEP-02", LocationUuid: "LOC-03", ManagerUuid: "EMP0008" },
                        { id: "EMP0004", EmployeeCode: "EMP0004", FirstName: "Ali", LastName: "Mansour", DepartmentName: "Operations", LocationName: "Dammam", Email: "ali.mansour@example.com", Phone: "+966500000004", Designation: "Operations Coordinator", JoiningDate: "2022-02-11", LeavingDate: "2023-12-01", Status: "Inactive", state: "None", SourceSystem: "Workday", ExternalEmployeeId: "EXT004", DepartmentUuid: "DEP-03", LocationUuid: "LOC-01", ManagerUuid: "EMP0009" },
                        { id: "EMP0005", EmployeeCode: "EMP0005", FirstName: "Omar", LastName: "Al-Fassi", DepartmentName: "HR", LocationName: "Jeddah", Email: "omar.alfassi@example.com", Phone: "+966500000005", Designation: "HR Specialist", JoiningDate: "2018-09-01", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Oracle HCM", ExternalEmployeeId: "EXT005", DepartmentUuid: "DEP-04", LocationUuid: "LOC-03", ManagerUuid: "EMP0010" },
                        { id: "EMP0006", EmployeeCode: "EMP0006", FirstName: "Fatima", LastName: "Zahra", DepartmentName: "Marketing", LocationName: "Riyadh", Email: "fatima.zahra@example.com", Phone: "+966500000006", Designation: "Marketing Manager", JoiningDate: "2020-11-15", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT006", DepartmentUuid: "DEP-05", LocationUuid: "LOC-02", ManagerUuid: "" },
                        { id: "EMP0007", EmployeeCode: "EMP0007", FirstName: "John", LastName: "Smith", DepartmentName: "IT", LocationName: "Dammam", Email: "john.smith@example.com", Phone: "+966500000007", Designation: "System Administrator", JoiningDate: "2021-08-01", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT007", DepartmentUuid: "DEP-01", LocationUuid: "LOC-01", ManagerUuid: "EMP0001" },
                        { id: "EMP0008", EmployeeCode: "EMP0008", FirstName: "Mona", LastName: "Ali", DepartmentName: "Finance", LocationName: "Riyadh", Email: "mona.ali@example.com", Phone: "+966500000008", Designation: "Finance Director", JoiningDate: "2017-04-10", LeavingDate: "", Status: "On Leave", state: "Warning", SourceSystem: "SAP HR", ExternalEmployeeId: "EXT008", DepartmentUuid: "DEP-02", LocationUuid: "LOC-02", ManagerUuid: "" },
                        { id: "EMP0009", EmployeeCode: "EMP0009", FirstName: "Khalid", LastName: "Abdulrahman", DepartmentName: "Operations", LocationName: "Jeddah", Email: "khalid.abdulrahman@example.com", Phone: "+966500000009", Designation: "Operations Manager", JoiningDate: "2016-01-20", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT009", DepartmentUuid: "DEP-03", LocationUuid: "LOC-03", ManagerUuid: "" },
                        { id: "EMP0010", EmployeeCode: "EMP0010", FirstName: "Jane", LastName: "Doe", DepartmentName: "HR", LocationName: "Dammam", Email: "jane.doe@example.com", Phone: "+966500000010", Designation: "HR Director", JoiningDate: "2015-05-15", LeavingDate: "2025-01-01", Status: "Inactive", state: "None", SourceSystem: "Oracle HCM", ExternalEmployeeId: "EXT010", DepartmentUuid: "DEP-04", LocationUuid: "LOC-01", ManagerUuid: "" },
                        { id: "EMP0011", EmployeeCode: "EMP0011", FirstName: "Hassan", LastName: "Tariq", DepartmentName: "IT", LocationName: "Riyadh", Email: "hassan.tariq@example.com", Phone: "+966500000011", Designation: "Network Engineer", JoiningDate: "2022-09-01", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT011", DepartmentUuid: "DEP-01", LocationUuid: "LOC-02", ManagerUuid: "EMP0001" },
                        { id: "EMP0012", EmployeeCode: "EMP0012", FirstName: "Leila", LastName: "Abbas", DepartmentName: "Marketing", LocationName: "Jeddah", Email: "leila.abbas@example.com", Phone: "+966500000012", Designation: "Content Strategist", JoiningDate: "2021-04-12", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT012", DepartmentUuid: "DEP-05", LocationUuid: "LOC-03", ManagerUuid: "EMP0006" },
                        { id: "EMP0013", EmployeeCode: "EMP0013", FirstName: "Yousef", LastName: "Kamal", DepartmentName: "Finance", LocationName: "Dammam", Email: "yousef.kamal@example.com", Phone: "+966500000013", Designation: "Accountant", JoiningDate: "2020-07-25", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "SAP HR", ExternalEmployeeId: "EXT013", DepartmentUuid: "DEP-02", LocationUuid: "LOC-01", ManagerUuid: "EMP0008" },
                        { id: "EMP0014", EmployeeCode: "EMP0014", FirstName: "Nadia", LastName: "Hussein", DepartmentName: "Operations", LocationName: "Riyadh", Email: "nadia.hussein@example.com", Phone: "+966500000014", Designation: "Logistics Analyst", JoiningDate: "2019-11-05", LeavingDate: "", Status: "On Leave", state: "Warning", SourceSystem: "Workday", ExternalEmployeeId: "EXT014", DepartmentUuid: "DEP-03", LocationUuid: "LOC-02", ManagerUuid: "EMP0009" },
                        { id: "EMP0015", EmployeeCode: "EMP0015", FirstName: "Tariq", LastName: "Aziz", DepartmentName: "IT", LocationName: "Jeddah", Email: "tariq.aziz@example.com", Phone: "+966500000015", Designation: "Helpdesk Support", JoiningDate: "2023-01-10", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT015", DepartmentUuid: "DEP-01", LocationUuid: "LOC-03", ManagerUuid: "EMP0001" },
                        { id: "EMP0016", EmployeeCode: "EMP0016", FirstName: "Aisha", LastName: "Rahman", DepartmentName: "HR", LocationName: "Riyadh", Email: "aisha.rahman@example.com", Phone: "+966500000016", Designation: "Recruiter", JoiningDate: "2021-02-28", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Oracle HCM", ExternalEmployeeId: "EXT016", DepartmentUuid: "DEP-04", LocationUuid: "LOC-02", ManagerUuid: "EMP0010" },
                        { id: "EMP0017", EmployeeCode: "EMP0017", FirstName: "Majid", LastName: "Al-Qahtani", DepartmentName: "Sales", LocationName: "Dammam", Email: "majid.alqahtani@example.com", Phone: "+966500000017", Designation: "Sales Executive", JoiningDate: "2018-05-14", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Salesforce", ExternalEmployeeId: "EXT017", DepartmentUuid: "DEP-06", LocationUuid: "LOC-01", ManagerUuid: "" },
                        { id: "EMP0018", EmployeeCode: "EMP0018", FirstName: "Reem", LastName: "Saeed", DepartmentName: "Marketing", LocationName: "Jeddah", Email: "reem.saeed@example.com", Phone: "+966500000018", Designation: "Graphic Designer", JoiningDate: "2022-10-01", LeavingDate: "2024-03-15", Status: "Inactive", state: "None", SourceSystem: "Workday", ExternalEmployeeId: "EXT018", DepartmentUuid: "DEP-05", LocationUuid: "LOC-03", ManagerUuid: "EMP0006" },
                        { id: "EMP0019", EmployeeCode: "EMP0019", FirstName: "Sami", LastName: "Abdullah", DepartmentName: "IT", LocationName: "Riyadh", Email: "sami.abdullah@example.com", Phone: "+966500000019", Designation: "Database Admin", JoiningDate: "2019-08-20", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "Workday", ExternalEmployeeId: "EXT019", DepartmentUuid: "DEP-01", LocationUuid: "LOC-02", ManagerUuid: "EMP0001" },
                        { id: "EMP0020", EmployeeCode: "EMP0020", FirstName: "Nour", LastName: "Yassin", DepartmentName: "Finance", LocationName: "Dammam", Email: "nour.yassin@example.com", Phone: "+966500000020", Designation: "Payroll Clerk", JoiningDate: "2023-05-01", LeavingDate: "", Status: "Active", state: "Success", SourceSystem: "SAP HR", ExternalEmployeeId: "EXT020", DepartmentUuid: "DEP-02", LocationUuid: "LOC-01", ManagerUuid: "EMP0008" }
                    ]
                });`;
    fileContent = fileContent.replace(match[0], newData);
    fs.writeFileSync('webapp/controller/Employees.controller.js', fileContent);
    console.log('Successfully replaced dummy data!');
} else {
    console.log('No match found.');
}
